### ISSUE TITLE
 'OWASP IDE-VulScanner' (version '1.0.1') is not compatible with the build is IC-232.9921.47

### ISSUE THREAD

**Issue by mohakawtar** [OWASP/www-project-ide-vulscanner#20]
Plugin 'OWASP IDE-VulScanner' (version '1.0.1') is not compatible with the current version of the IDE, because it requires build 223.* or older but the current build is IC-232.9921.47

**Comment by Jitu-Ranjan** [comment]
A new version is uploaded, perform an update to 1.0.2 once released in market place.
