### ISSUE TITLE
Not compatible with latest IntelliJ

### ISSUE THREAD

**Issue by stefanerwinmayer** [OWASP/www-project-ide-vulscanner#21]
**Intellij version:**
IntelliJ IDEA 2023.2.5 (Ultimate Edition)
Build #IU-232.10227.8, built on November 9, 2023

**What was downloaded:**
https://plugins.jetbrains.com/files/21353/313112/OWASP_IDE-VulScanner-1.0.0.zip

**What happens during install:**
![owasp](https://github.com/OWASP/www-project-ide-vulscanner/assets/15031950/0b54b4ac-de4e-489c-a41a-d6b6ab128837)

**Comment by Jitu-Ranjan** [comment]
Have you tried downloading 1.0.2 version?

**Comment by stefanerwinmayer** [comment]
I would have had the download link on the README lead to that version.
